### ISSUE TITLE
Problem with MoreCheckmarks

### ISSUE THREAD

**Issue by kurwabober2** [CathieNova/SPT-Haven-Industries-Chloe#1]
When installing the mod, MoreCheckmarks stops working.

2024-11-25 16:32:35.874 +03:00|0.14.9.1.30626|Error|Default| 
EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object
  at MoreCheckmarks.MoreCheckmarksMod.LoadData () [0x005cb] in <9f9f0487d84c4a3199903c07dc66afb1>:0 
  at MoreCheckmarks.MoreCheckmarksMod.Init () [0x00039] in <9f9f0487d84c4a3199903c07dc66afb1>:0 
  at MoreCheckmarks.MoreCheckmarksMod.Start () [0x00016] in <9f9f0487d84c4a3199903c07dc66afb1>:0 
2024-11-25 16:32:35.877 +03:00|0.14.9.1.30626|Error|Default|NullReferenceException: Object reference not set to an instance of an object
MoreCheckmarks.MoreCheckmarksMod.LoadData () (at <9f9f0487d84c4a3199903c07dc66afb1>:0)
MoreCheckmarks.MoreCheckmarksMod.Init () (at <9f9f0487d84c4a3199903c07dc66afb1>:0)
MoreCheckmarks.MoreCheckmarksMod.Start () (at <9f9f0487d84c4a3199903c07dc66afb1>:0)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
Class362:UnityEngine.ILogHandler.LogException(Exception, Object)
UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)

**Comment by kurwabober2** [comment]
There doesn't seem to be a problem in the merchant mod itself. It's somewhere in the quests.

**Comment by CathieNova** [comment]
Should be fixed now.

**Comment by kurwabober2** [comment]
Can you please tell me in which file the edit was? So that I can throw only this file, since I translated the mod into Russian, I would not like to transfer the translation again.

**Comment by kurwabober2** [comment]
Also on the Virtual's Custom Quest Loader\database\quests path in the 0_The_Deadweight_Test file there are differences in find and pass, which will not work correctly when completing the quest.

**Comment by kurwabober2** [comment]
![Снимок экрана 2024-11-26 194556](https://github.com/user-attachments/assets/69a0f708-4f4c-4b3a-9176-3e62e0fbd06f)
