### ISSUE TITLE
Differences in 0_The_Deadweight_Test

### ISSUE THREAD

**Issue by kurwabober2** [CathieNova/SPT-Haven-Industries-Chloe#3]
Also on the Virtual's Custom Quest Loader\database\quests path in the file there are differences in find and pass, which will not work correctly when completing the quest.

![Снимок экрана 2024-11-26 194556](https://github.com/user-attachments/assets/82a1d204-ddeb-4634-a2d1-c9fd6ecd98bd)

**Comment by CathieNova** [comment]
I'll fix that as soon as i get time! ^_^
