### ISSUE TITLE
Wiafu Drop rate

### ISSUE THREAD

**Issue by CrankyYoda** [CathieNova/SPT-Haven-Industries-Chloe#5]
I am finding the card drop rates  intrusive  they  replace  rather than inject can we get a toggle on off for cards or a global  probability rather than the granular by  container for every card.. unless its there and I cant find it ..  very possible  also I have attached a screen shot of keys that are missing from the containers,  it isnt exhaustive ill update it as I find more

![keys011224](https://github.com/user-attachments/assets/7d1a70e3-225e-4b95-9632-b5c69644bb58)

**Comment by CathieNova** [comment]
The droprate has been reduced and balanced but not uploaded yet.

What is wrong with the keychains? what keys are missing?

**Comment by CrankyYoda** [comment]
sounds good...

the keys in the keytool wont slot into their respective holders just says incompatible ie TGL MO isn't in the holder on the right and is incompatible  with the holder.

**Comment by CathieNova** [comment]
That just confused me..
Please describe what is wrong, for example if a key does not work for Keychain 5 then say what should be added to it.

I added all keys i found on the eft wiki (i might have missed a few)

**Comment by CrankyYoda** [comment]
okay so the keys in the keytool on the right  SHOULD go into  their respective key holder  but they don't. Just says incompatible  or  don't have a slot allocated. Example  keyholder on the left is missing the TGL  keys, which I have in the key tool on the left but they will not slot in says incompatible.

Keys like  Voron  overseer and the  ground zero keys   don't have a slot allocated for them to go into .

**Comment by CathieNova** [comment]
oh alright, i'll do another sweep to see what i have missed
