### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'some')

### ISSUE THREAD

**Issue by jhohns7** [CathieNova/SPT-Haven-Industries-Chloe#6]
TypeError: Cannot read properties of undefined (reading 'some')
    at CustomHideoutCraftService.postDBLoad (A:\SPT\user\mods\Haven Industries - Chloe\src\CustomHideoutCraftService.ts:41:49)
    at SampleTrader.postDBLoad (A:\SPT\user\mods\Haven Industries - Chloe\src\mod.ts:93:40)
    at PostDBModLoader.executeModsAsync (C:\snapshot\src\loaders\PostDBModLoader.ts:63:45)
    at PostDBModLoader.onLoad (C:\snapshot\src\loaders\PostDBModLoader.ts:26:24)
    at App.load (C:\snapshot\src\utils\App.ts:51:26)

Here is a list of the errors I receive when loading the server with the mod installed. 

I have made the adjustments for SVM as recommended. 

Other mods I have installed are:

aMoxoPixel-Painter
CoyoteTrader
HoodsEnergyDrinks
limbofps-realisticbosshp
Olympus
radomizzatore-morecases
samswat-reflexsightsrework
SVM
unbreakable-keys
VCQL

**Comment by CathieNova** [comment]
Did you change anything in regards to SVM with hideout?

**Comment by jhohns7** [comment]
No, I have only made edits to Inventory, loot, and raid settings

**Comment by CathieNova** [comment]
Alright, There will be an update coming soon so it fixes a lot of things.

For the time being you can replace this file 
[CustomHideoutCraftService.zip](https://github.com/user-attachments/files/18004006/CustomHideoutCraftService.zip)
 inside `\user\mods\Haven Industries - Chloe\src` it should fix your issue.

**Comment by jhohns7** [comment]
It's still giving me the same issue..

**Comment by CathieNova** [comment]
That's really weird, both works for me...

**Comment by CathieNova** [comment]
Try to delete the files:
> CustomHideoutCraftService.js
> CustomHideoutCraftService.js.map

Then launch the server again

**Comment by jhohns7** [comment]
giving me the same code, but now instead of (reading 'some') it states (reading 'concat')

**Comment by CathieNova** [comment]
I dont' quite understand why it's not working for you as it gives me no errors...

**Comment by jhohns7** [comment]
idk, im gonna try a fresh install of spt to see if that fixes it

**Comment by jhohns7** [comment]
idk why but a fresh spt install fixed it, i literally installed it yesterday, thanks for the help!
