### ISSUE TITLE
'The mole has our loot'

### ISSUE THREAD

**Issue by Triggan1488** [CathieNova/SPT-Haven-Industries-Chloe#7]
The quest 'The mole has our loot' doesn't work. I can't place a mark either near the corpse, in the corpse's inventory, or near the car. After the update, I completely deleted the mod and the quests folder. Perhaps the fact is that the quest is for an entry-level PMC and I have 40lv?

**Comment by CathieNova** [comment]
If you are above level 21 then you can replace the zone in `user\mods\Virtual's Custom Quest Loader\database\zones\Ground Zero` with this file
[saving_the_mole.json](https://github.com/user-attachments/files/18014663/saving_the_mole.json)

**Comment by Triggan1488** [comment]
After replacing the file everything worked. Thanks nice mod. But in a quest where you need to give up a video card, giving 3 bolts as a reward is a meme)
