### ISSUE TITLE
Not an issue just a note

### ISSUE THREAD

**Issue by CrankyYoda** [CathieNova/SPT-Haven-Industries-Chloe#8]
With the update to keychains if you have  old ones you will need to remove your keys  delete the old keychains and buy new ones for the key slots to open up.. tried and tested

**Comment by CathieNova** [comment]
Oh i forgot to mention that in the changelog, i will fix that now.

**Comment by CrankyYoda** [comment]
![Uploading final quest LL.jpg…]()

**Comment by CrankyYoda** [comment]
![final quest LL](https://github.com/user-attachments/assets/84e49013-1c7c-4efe-a9d7-380fed726d0c)

**Comment by CathieNova** [comment]
Was this with standard profile?

**Comment by CrankyYoda** [comment]
unheard  but not a reset profile my guess is a mismatch between  old version quest rewards and new version just waiting for sain and questing bots to do a wipe

**Comment by CathieNova** [comment]
Could be, though i am not done with the quests as there will be many more but it takes time and i lack that :/

**Comment by CrankyYoda** [comment]
So i went through the quests and total raw  traderstanding  rewards is 0.685 so max lvl trader  at 1.50 is unobtainable at this point

**Comment by CathieNova** [comment]
There is nothing to get at level 4 Chloe, Level 3 is the last tier any items is at for the moment
